### ISSUE TITLE
html tag replacement

### ISSUE THREAD

**Issue by hamishgibbs** [lshtm-gis/WHO_PHSM_Cleaning#5]
It looks as if the </p> replacement might have gone awry this week - I've got a few instance of a lower case p at the start of a sentence.  Plus some /pp&nbsp/pp which might be a new thing to check for.

**Comment by hamishgibbs** [comment]
Do we have any examples of the WHO ids for this?

**Comment by OIQuinn** [comment]
CDC-ITF-AU-00111: Pstrong

CDC-ITF-AU-00124: a&nbspand

CDC-ITF-AT-00068: &nbsp

CDC-ITF-BD-00067: /pp&nbsp/ppa href"

**Comment by OIQuinn** [comment]
Removal of html tags from the comments field needs revisiting (examples plus sample who_id below):
&nbsp  CDC-ITF-DE-00092
&nbsp/pp CDC-ITF-FR-00100
./strong/ppstrong&nbsp/strong/ppstrong  CDC-ITF-IT-00073

**Comment by OIQuinn** [comment]
New this week: "/lili" in the comments

**Comment by hamishgibbs** [comment]
Alright - I have added the removal of the non breaking space `&nbsp`. 

I fear that a few of these are coming from a past week when we aggressively removed the `<` and `>` characters (which was an error). This left lots of html tags without brackets - which has led to strings like `/lili` which used to be two HTML list elements `</li><li>` and could easily have been removed, now it may be harder to get the HTML tags out of the record from that week.

**Comment by hamishgibbs** [comment]
Have also resolved the removal of brackets later in the procecessing routine. Hopefully this is resolved incoming weeks.

**Comment by OIQuinn** [comment]
New one this week. 
Example in CDC-ITF-MQ-00007:

format:&nbsp;PDF&nbsp;- 0.05 Mb

**Comment by OIQuinn** [comment]
Also still receiving &nbsp;</strong><strong>

CDC-ITF-MQ-00005

**Comment by hamishgibbs** [comment]
We have tracked down the encoding issue - it is a problem with opening UTF-8 encoded csv files in Excel. I will start outputting the data as ANSI encoded. This is open in #69.

**Comment by OIQuinn** [comment]
Ã¢â‚¬Â¢ appearing in comments

**Comment by hamishgibbs** [comment]
`Ã¢â‚¬Â¢` looks like an issue with encoding which is addressed in #69, not a missed HTML tag. I will address that issue asap and am going to close this issue for the time being.
